19.1.0: Deleted old files and imported new from NetSuite

diff --git a/Files/bin/Mac/sdfcli b/Files/bin/Mac/sdfcli
--- a/Files/bin/Mac/sdfcli
+++ b/Files/bin/Mac/sdfcli
@@ -1,54 +1,30 @@
 #!/bin/bash
-SDFSDK_PATH=/webdev/sdf/sdk/
 
-if [ ! -d "$SDFSDK_PATH" ]; then
-    clear
-    echo ""
-    echo "ERROR: SDF SDK was not found in $SDFSDK_PATH."
-    echo ""
-    echo "Edit this batch file and set the SDFSDK_PATH variable to"
-    echo "the correct path of your SDF SDK installation."
-    echo ""
-    echo "For more information about SDF SDK installation, see:"
-    echo "https://system.netsuite.com/app/help/helpcenter.nl?fid=section_1489072409.html"
+supported_java_version=1.8
+cli_jar_file_name="cli-2019.1.0.jar"
+
+msg_java_not_installed="Java Runtime Environment is not installed on this machine. Install JRE version $supported_java_version to run SDF CLI."
+msg_java_incompatible_version="Your Java version is not compatible with SDF CLI. Install JRE version $supported_java_version."
+msg_jar_file_missing="The JAR file could not be found. Download the JAR file from the Help Center into the same directory where the SDF CLI script is stored."
+
+installed_java_version=$(java -fullversion 2>&1 | awk -F '"' '/version/ {print $2}')
+if [[ "$installed_java_version" == "" ]]; then
+    echo "$msg_java_not_installed"
+    exit 1
+elif [[ "$installed_java_version" != "$supported_java_version"* ]]; then
+    echo "$msg_java_incompatible_version"
     exit 1
 fi
 
-SDFSDK_JAR=($SDFSDK_PATH/com.netsuite.ide.core_*.jar)
-if [ ! -f $SDFSDK_PATH/pom.xml ] || [ ! -e ${SDFSDK_JAR[0]} ]; then
-    clear
-    echo ""
-    echo "ERROR: A file was missing from $SDFSDK_PATH."
-    echo ""
-    echo "The following files are required to run SDF CLI:"
-    echo "    - axis.jar"
-    echo "    - com.netsuite.ide.core_<NetSuite-version>.jar"
-    echo "    - NetSuiteWebService.jar"
-    echo "    - pom.xml"
-    echo ""
-    echo "Check your SDF SDK installation path, and make sure that you"
-    echo "downloaded or extracted the files listed above."
-    echo ""
-    echo "For more information about SDF SDK installation, see:"
-    echo "https://system.netsuite.com/app/help/helpcenter.nl?fid=section_1489072409.html"
+cli_directory=$(dirname "$BASH_SOURCE")
+cli_jar_file_path="$cli_directory/$cli_jar_file_name"
+
+if [ ! -f "$cli_jar_file_path" ]; then
+    echo "$msg_jar_file_missing"
     exit 1
 fi
 
-if [ ! -f $SDFSDK_PATH/axis.jar ] || [ ! -f $SDFSDK_PATH/NetSuiteWebService.jar ]; then
-    clear
-    echo ""
-    echo "ERROR: Could not find axis.jar or NetSuiteWebService.jar."
-    echo ""
-    echo "axis.jar or NetSuiteWebService.jar must be extracted from the"
-    echo "com.netsuite.ide.eclipse.ws JAR file and placed in the"
-    echo "$SDFSDK_PATH folder."
-    echo ""
-    echo "Oracle recommends using an unzip utility to extract the contents of the"
-    echo "com.netsuite.ide.eclipse.ws JAR file into the $SDFSDK_PATH folder."
-    echo ""
-    echo "For more information about SDF SDK installation, see:"
-    echo "https://system.netsuite.com/app/help/helpcenter.nl?fid=section_1489072409.html"
-    exit 1
-fi
+java -jar "$cli_jar_file_path" $*
 
-mvn -f $SDFSDK_PATH/pom.xml exec:java -Dexec.args="$*"
+
+
